---
output:
  html_document:
    css: "www/css/modest.css"
---

```{r setup, include=FALSE, echo=FALSE}
library(htmltools)
library(vembedr)
library(shiny)
# You can include R code or R shiny apps (I think) here
```

## Professional Experience

### Senior Advisor, Quantitative Medicine
#### Critical Path Institute (C-Path)
###### Apr 2020 – Present • North Wales, Pennsylvania, United States
 - Serve as critical liaison between C-Path and the pharmaceutical industry, foundations, and other key stakeholders, and help grow C-Path’s portfolio in drug development solutions, with a focus, but not limited to MIDD.
 - Member of the executive leadership team with specific duties to:
   - Advise on the development of data and analytics platforms
   - Lead the interactions with the academic partner for the FDA MIDD training course
   - Advise the QuantMed program, leading the creation of a monetized training program for industry scientists on the quantitative tools C-Path develops
   - Connect with organizations for collaboration and business opportunities.
   - Define a strategy for business development for C-Path, focusing on (but not limited to), the generation of solutions for medical product development.
   - Leverage C-Path standing within the pharmaceutical industry and FDA community, to establish targeted monetized MIDD training opportunities for industry scientists on the use of MIDD solutions developed by C-Path, as well as other relevant MIDD areas.
   - Serve as an expert internal trainer for MIDD approaches, to help QuantMed Program scientists expand their skillsets in relevant quantitative methods.
   - Serve as an expert in supporting the development of FDA’s MIDD training course, leading discussions with academic partners, and supporting the oversight and supervision of the project.
   - Support the hands-on development of MIDD solutions, as relevant, across QuantMed programmatic activities.
   - Support the Chief Science Officer and the Chief Technology Officer in the design of data and analytics platforms.
   - Support the CEO and CSO in defining a strategy for the development of MIDD solutions for pediatric populations, in partnership with the CSO and the Scientific Director of Pharmacometrics.

<hr>

### Head Quantitative Sciences
#### Bill & Melinda Gates Medical Research Institute 
###### Mar 2018 – Apr 2020; Consultant Apr 2020 - Present • Cambridge, MA, United States
 - Accountable for leading The Institute in drug and vaccine development through the implementation of model-based drug development and employing PK/PD modeling, statistics, and clinical trial simulations. The role also provides support for other Institute efforts requiring development/quantitative support including vector control, diagnostics, and product development. 
 - Participates in the decision making and overall operations of the Institute and helps to build the new organization including modeling and driving the desired culture, hiring individuals with the talent, drive, and skills to achieve the Institute mission, and providing input on systems and the overall operating model. 
 - Building and managing a team that is responsible for establishing the modeling, biostatistics, bioinformatics, and DMPK function for the Institute.

<hr>

### Vice President, Translational Informatics
#### Sanofi
###### Mar 2016 – Mar 2018 • Bridgewater, NJ, United States
 - Translational Informatics (TI) comprises Quantitative Systems Pharmacology, Bioinformatics & Data Integration, Drug-disease modeling and Clinical Trial Simulation groups within Sanofi. The global group includes 34 quantitative scientists that participate in various aspects of model-based decision making spanning from drug discovery through commercialization. The group is positioned to provide strategic guidance to project teams and various decision making bodies as well as senior management.
 - Leadership for R&D’s cloud-based, high-performance computing and several big data initiatives is also provided in collaboration with IS and IT collaborators and external technology partners.
 - The Global Head of Pediatric Clinical Pharmacology role provides support to all pediatric clinical development plans and regulatory filing strategy. The co-leadership of the Sanofi Pediatric Network advises project teams on design, conduct and analysis. PhRMA topic leader for ICH E11A working group on pediatric extrapolation of efficacy.

<hr>

### Vice President, Interdisciplinary Pharmacometrics Program
#### Sanofi
###### Nov 2013 – Mar 2018 • Bridgewater, NJ, United States
 - Leader of modeling and simulation efforts across the Scientific Core Platforms -- developing, testing, and exploiting quantitative relationships to facilitate critical decisions that span the drug discovery and development process. The IPP ensures that modeling aspects are covered in an integrated way across the platforms, bringing together the multiple disciplines, and that resources are applied with priority to the most important questions and projects. I also serve as the Global Head of Pediatric Clinical Pharmacology and lead Sanofi's Pediatric Network which advises project teams.

<hr>

### Professor, Pediatrics and Pharmacology
#### The Children's Hospital of Philadelphia
###### May 2003 – Nov 2013 • Philadelphia, PA, United States
 - Principal Investigator for the CHOP Pediatric Pharmacology Research Unit (PPRU) and the Director of the Penn/CHOP Kinetic Modeling and Simulation ([KMAS](https://www.med.upenn.edu/kmas/)) core of the CTSA. Research is focused on the investigation of sources of variation in pediatric pharmacokinetics. Applied clinical pharmacologic investigation coupled with modeling and simulation strategies are pursued with the intention of developing rational dosing guidance in various pediatric populations for both marketed and exploratory compounds. Clinical trial simulation is utilized prospectively to explore design dependencies and parameter sensitivities. The Laboratory for Applied PK/PD is focused on the development of novel pharmacometric approaches, biomarker development and disease progression modeling.

<hr>

### Global Head, Biopharmaceutics
#### Aventis Pharmaceuticals
###### Apr 2001 – Apr 2003 • Bridgewater, NJ, United States
 - Managed 13 scientists worldwide to support late stage development (Phase IIb through post marketing) with an annual budget of $25 million Euro. Responsibilities included the conduct and regulatory submission preparation of definitive clinical bioavailability and bioequivalence and related manufacturing specification studies, formulation development and screening trials, population pharmacokinetics, late stage drug interaction and special population studies, and mechanistic PK characterization.

<hr>

### Director, Clinical Pharmacokinetics
#### DuPont Pharmaceuticals
###### 1996 – 2000
 - Directed the Clinical PK effort in support of the cardiovascular and CNS franchises as well as the IT support of the DM&PK department. Conduct preclinical and clinical aspects of drug development including bioanalytical, toxicokinetic, pharmacokinetic, and pharmacodynamic support. Functional responsibilities include protocol design, toxicokinetic, pharmacokinetic, pharmacodynamic analyses and reporting for pre-NDA and NDA development stages, FDA liaison, and bioanalytical site selection. Supervisory responsibilities include the management of 3 PhD scientists, 1 web-programmer, 1 data warehouse administrator, and 2 junior staff scientists.
 - Co-authored population pharmacokinetic analysis reports for Sustiva and innohep NDAs. Co-authored Biopharmaceutics Sections for Morphine Sulfate CR ANDA and innohep NDA. Initiated data warehousing efforts for department including intranet-based access and exploitation tools. Developed novel biomarkers for Factor Xa inhibitor program. Company representative for co-development of SAS PH-Kinetics non-compartmental pharmacokinetic analysis application. Departmental representative for R&D Bioinformatics initiative.

<hr>

### Director, Clinical Pharmacokinetics & Computer Resources
#### Somerset Pharmaceuticals
###### 1994 – 1996
 - Conduct preclinical and clinical aspects of drug development, contract all bioanalytical and clinical services, supervise database management of post marketing and ongoing clinical drug safety surveillance programs, develop flexible data entry system for monitoring of clinical laboratory and adverse event data from ongoing development programs, and provide hardware and software support for the Somerset PC network. Functional responsibilities include protocol design, study monitoring, toxicokinetic, pharmacokinetic, pharmacodynamic and statistical analyses and reporting, FDA liaison, clinical and bioanalytical site selection, the management of all R&D computer resources, and supervision of six people (pharmacokineticist, statistician, programmers, CRAs).
 - Completed numerous Phase-I studies in healthy male volunteers, healthy elderly men and women, post-menopausal women, and SDAT patients in support of the selegiline transdermal system and ipriflavone development programs and product line extensions for Eldepryl. Authored Biopharmaceutics Section for Eldepryl Capsule ANDA. Completed acute, subacute and chronic toxicology studies, in vitro topical metabolism, and pharmacology studies in support of the selegiline transdermal system and ipriflavone development programs.




